version: "3.6"

services:
  face-detect-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/face-detect-api
    environment:
      POSTGRES_URI: postgres://user:secret@postgres:5432/face-detect-docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/face-detect-api

  # Postgres
  postgres:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: face-detect-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
